package cloudformation

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

// DownloadCloudFormationTemplate provides the template as a downloadable YAML file
func DownloadCloudFormationTemplate(ctx *gin.Context) {
	var request CloudFormationRequest
	if err := ctx.ShouldBindJSON(&request); err != nil {
		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid request"})
		return
	}

	// Get the appropriate template filename
	templateFile := getTemplateFilename(request.AccessTier)
	if templateFile == "" {
		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid AccessTier"})
		return
	}

	// Read the CloudFormation template file
	templateContent, err := os.ReadFile(templateFile)
	if err != nil {
		log.Printf("Error reading template file: %v", err)
		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to read template file"})
		return
	}

	// Generate a unique external ID
	externalID := generateExternalID()

	// Modify the template with the external ID
	modifiedTemplate := modifyTemplateWithExternalID(string(templateContent), externalID)

	// Set headers for file download
	filename := fmt.Sprintf("cloudloom-%s-template.yaml", strings.ToLower(request.AccessTier))
	ctx.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%s", filename))
	ctx.Header("Content-Type", "application/x-yaml")
	ctx.Header("X-External-ID", externalID) // Include external ID in headers for reference

	// Return the YAML content directly
	ctx.String(http.StatusOK, modifiedTemplate)
}

// generateExternalID creates a unique external ID for cross-account access
func generateExternalID() string {
	return fmt.Sprintf("cloudloom-%s", uuid.New().String())
}

// getTemplateFilename returns the appropriate template filename based on access tier
func getTemplateFilename(accessTier string) string {
	switch accessTier {
	case CloudLoomNotificationTier:
		return "cloudformation-templates/cloud-insight.yaml"
	case CloudLoomSuggestFixTier:
		return "cloudformation-templates/cloud-advisor.yaml"
	case CloudLoomAutoApplyFixTier:
		return "cloudformation-templates/cloud-guardian.yaml"
	default:
		return ""
	}
}

// modifyTemplateWithExternalID adds the generated external ID as a default value in the template
func modifyTemplateWithExternalID(templateContent, externalID string) string {
	// Replace the ExternalId parameter section to include the generated external ID as default
	oldExternalIdSection := `  ExternalId:
    Type: String
    Description: A unique identifier provided by CloudLoom for cross-account access security.
    MinLength: 10
    MaxLength: 100 # This should be a unique ID generated by your CloudLoom application for each user.`

	newExternalIdSection := fmt.Sprintf(`  ExternalId:
    Type: String
    Description: A unique identifier provided by CloudLoom for cross-account access security.
    Default: "%s" # Generated External ID - Use this value when deploying
    MinLength: 10
    MaxLength: 100`, externalID)

	return strings.ReplaceAll(templateContent, oldExternalIdSection, newExternalIdSection)
}
